baseurl = "https://clb6.github.io/"
languageCode = "en-us"
title = "CLB6"

theme = "hyde-y"

[permalinks]
    project = "/project/:slug"

[author]
    name = "Michael Hwang"
    email = "hirehwang@gmail.com"

[params]
    # You can use markdown here.
    brand = "CLB6"
    topline = "Curating lives bit-by-bit, byte-by-byte"
    #footline = "code with <i class='fa fa-heart'></i>"

    # Sidebar position
    # false, true, "left", "right"
    sidebar = "left"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    home = "Home"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "default"

    github = "clb6"
